### ISSUE TITLE
NewClient should also take baseURL as param to support remote or local connection

### ISSUE THREAD

**Issue by theCipherBlock** [manishmeganathan/go-moibit-sdk#1]

**Comment by manishmeganathan** [comment]
We can implement a BaseURL customization as another option on the ``Client`` object.
This would require the URL constants to be restructured as a lookup method on ``Client``.

The ``func BaseURL(url string) ClientOption`` option accepts a URL which is then appended with endpoints such ``/user/auth`` and ``makedir``. The default BaseURL value must be ``https://api.moinet.io/moibit/v1``.

The point of this customization is to use the Client with a local MOIBit instance or a development instance.

**Comment by manishmeganathan** [comment]
c0a0516 Adds support for Base URL Customization on the Client with a ``BaseURL`` generator for a ``ClientOption`` that can be passed into the constructor of Client

**Comment by manishmeganathan** [comment]
#2 Merged with Functionality
